services:
  sage.test:
    build:
      dockerfile: Dockerfile
    image: sage.m/dev-8.2
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      XDEBUG_MODE: '${XDEBUG_MODE:-develop,debug}'
      XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_port=9003 client_host=host.docker.internal discover_client_host=true}'
    volumes:
      - app:/app/www
      - .:/app/build
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql
      - mailpit
      - redis
    networks:
      - sage

  web:
    image: nginx:stable-alpine
    volumes:
      - app:/app/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${FORWARD_NGINX_PORT:-80}:80
    environment:
      NGINX_HOST: '${WP_HOME:-127.0.0.1}'
    links:
      - sage.test:php-upstream
    networks:
      - sage

  mysql:
    image: mysql:8.0
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_HOST: '127.0.0.1'
      MYSQL_DATABASE: '${DB_NAME:-sage}'
      MYSQL_USER: '${DB_USER:-sage}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - sage

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - ${FORWARD_MAILPIT_PORT:-1025}:1025
      - ${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025
    networks:
      - sage

  redis:
    image: redis:alpine
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - cache:/data
    networks:
      - sage

volumes:
  app:
  database:
  cache:

networks:
  sage:
